### ISSUE TITLE
Update background

### ISSUE THREAD

**Issue by Icyscools** [Icyscools/itfreshy-minigame-3card#2]
Please find background to make my game to more charming.

![image](https://user-images.githubusercontent.com/30778789/96328414-e9cd7280-106c-11eb-975b-c7230e63e562.png)

Please put image to `/assets` folder.

P.S. Make sure not to use license image background!

**Comment by NAPATKRUP** [comment]
I want to do this

**Comment by Icyscools** [comment]
Ok, I'll assign this issue for you.
